#!/usr/bin/env bash

function del_link {
    sudo unlink /usr/local/bin/pacapt-tlmgr
    sudo unlink /usr/local/bin/pacapt-conda
    sudo unlink /usr/local/bin/p-tlmgr
    sudo unlink /usr/local/bin/p-conda
    sudo unlink /usr/local/bin/pacman
    return 0
}
del_link